"""initial schema

Revision ID: a5e311f44cf1
Revises: 
Create Date: 2026-08-27 20:26:35.274597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e311f44cf1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('ai_provider', sa.String(length=30), nullable=True),
    sa.Column('ai_model', sa.String(length=80), nullable=True),
    sa.Column('ai_api_key', sa.String(length=300), nullable=True),
    sa.Column('ai_base_url', sa.String(length=300), nullable=True),
    sa.Column('allow_ai_processing', sa.Boolean(), nullable=False),
    sa.Column('ai_monthly_limit_usd', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('lead_distribution', sa.String(length=20), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_insights',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dedup_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_insights_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insights_dedup_key'), ['dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insights_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_insights_org_kind_status', ['organization_id', 'kind', 'status'], unique=False)

    op.create_table('automations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automations_organization_id'), ['organization_id'], unique=False)

    op.create_table('feature_flags',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'key', name='uq_flag_org_key')
    )
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_flags_organization_id'), ['organization_id'], unique=False)

    op.create_table('pipeline_stages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('is_won', sa.Boolean(), nullable=False),
    sa.Column('is_lost', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'key', name='uq_stage_org_key')
    )
    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_stages_organization_id'), ['organization_id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_tag_org_name')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_organization_id'), ['organization_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('avatar_color', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=128), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_reset_token'), ['reset_token'], unique=False)

    op.create_table('ai_usage',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('feature', sa.String(length=40), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_organization_id'), ['organization_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_audit_org_created', ['organization_id', 'created_at'], unique=False)

    op.create_table('automation_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('automation_id', sa.String(length=32), nullable=False),
    sa.Column('trigger_entity_type', sa.String(length=30), nullable=True),
    sa.Column('trigger_entity_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_runs_automation_id'), ['automation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_runs_organization_id'), ['organization_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('dedup_key', sa.String(length=120), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_dedup_key'), ['dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read_at'], unique=False)

    op.create_table('segments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('entity', sa.String(length=20), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segments_organization_id'), ['organization_id'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('brand', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=120), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('km', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
    sa.Column('plate', sa.String(length=20), nullable=True),
    sa.Column('fuel', sa.String(length=20), nullable=False),
    sa.Column('transmission', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('body_type', sa.String(length=20), nullable=False),
    sa.Column('doors', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('assigned_user_id', sa.String(length=32), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('sold_price', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
    sa.Column('buyer_customer_id', sa.String(length=32), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index('ix_vehicles_org_brand_model', ['organization_id', 'brand', 'model'], unique=False)
        batch_op.create_index('ix_vehicles_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_plate'), ['plate'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('whatsapp', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_user_id', sa.String(length=32), nullable=True),
    sa.Column('interested_vehicle_id', sa.String(length=32), nullable=True),
    sa.Column('budget', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
    sa.Column('financing_interest', sa.Boolean(), nullable=False),
    sa.Column('has_trade_in', sa.Boolean(), nullable=False),
    sa.Column('interest_brand', sa.String(length=60), nullable=True),
    sa.Column('interest_model', sa.String(length=80), nullable=True),
    sa.Column('interest_body_type', sa.String(length=20), nullable=True),
    sa.Column('interest_year_min', sa.Integer(), nullable=True),
    sa.Column('interest_year_max', sa.Integer(), nullable=True),
    sa.Column('interest_transmission', sa.String(length=20), nullable=True),
    sa.Column('interest_fuel', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('score_label', sa.String(length=12), nullable=False),
    sa.Column('score_reason', sa.String(length=300), nullable=True),
    sa.Column('score_factors', sa.JSON(), nullable=False),
    sa.Column('score_updated_at', sa.DateTime(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_summary_at', sa.DateTime(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.Column('last_inbound_at', sa.DateTime(), nullable=True),
    sa.Column('last_outbound_at', sa.DateTime(), nullable=True),
    sa.Column('next_followup_at', sa.DateTime(), nullable=True),
    sa.Column('first_response_seconds', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['interested_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_assigned_user_id'), ['assigned_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_interested_vehicle_id'), ['interested_vehicle_id'], unique=False)
        batch_op.create_index('ix_customers_org_assigned', ['organization_id', 'assigned_user_id'], unique=False)
        batch_op.create_index('ix_customers_org_score', ['organization_id', 'lead_score'], unique=False)
        batch_op.create_index('ix_customers_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)

    op.create_table('vehicle_images',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('vehicle_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_images_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_images_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('vehicle_status_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('vehicle_id', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_status_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_status_history_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_status_history_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('vehicle_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('ix_appointments_org_starts', ['organization_id', 'starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_user_id'), ['user_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_user_id', sa.String(length=32), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index('ix_conversations_org_last', ['organization_id', 'last_message_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_organization_id'), ['organization_id'], unique=False)

    op.create_table('customer_notes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_notes_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_notes_organization_id'), ['organization_id'], unique=False)

    op.create_table('customer_tags',
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('tag_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'tag_id')
    )
    op.create_table('customer_vehicle_matches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('vehicle_id', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'vehicle_id', name='uq_match_customer_vehicle')
    )
    with op.batch_alter_table('customer_vehicle_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_vehicle_matches_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_vehicle_matches_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_vehicle_matches_vehicle_id'), ['vehicle_id'], unique=False)
        batch_op.create_index('ix_matches_org_status', ['organization_id', 'status'], unique=False)

    op.create_table('lead_score_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('old_score', sa.Integer(), nullable=False),
    sa.Column('new_score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_score_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_score_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_score_history_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_score_history_organization_id'), ['organization_id'], unique=False)

    op.create_table('opportunities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('vehicle_id', sa.String(length=32), nullable=True),
    sa.Column('owner_user_id', sa.String(length=32), nullable=True),
    sa.Column('stage_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('health', sa.String(length=10), nullable=False),
    sa.Column('lost_reason', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('expected_close_date', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stages.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index('ix_opportunities_org_stage', ['organization_id', 'stage_id'], unique=False)
        batch_op.create_index('ix_opportunities_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_stage_id'), ['stage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_due_at'), ['due_at'], unique=False)
        batch_op.create_index('ix_tasks_org_status_due', ['organization_id', 'status', 'due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('financing_scenarios',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=True),
    sa.Column('vehicle_id', sa.String(length=32), nullable=True),
    sa.Column('vehicle_price', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('down_payment', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('financed_amount', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('annual_rate', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=False),
    sa.Column('monthly_payment', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financing_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financing_scenarios_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financing_scenarios_organization_id'), ['organization_id'], unique=False)

    op.create_table('followups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('suggested_reason', sa.String(length=300), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_followups_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_followups_due_at'), ['due_at'], unique=False)
        batch_op.create_index('ix_followups_org_status_due', ['organization_id', 'status', 'due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_followups_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_followups_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_conv_created', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_organization_id'), ['organization_id'], unique=False)

    op.create_table('opportunity_stage_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=False),
    sa.Column('from_stage_id', sa.String(length=32), nullable=True),
    sa.Column('to_stage_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_stage_id'], ['pipeline_stages.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['to_stage_id'], ['pipeline_stages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunity_stage_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_stage_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_stage_history_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_stage_history_organization_id'), ['organization_id'], unique=False)

    op.create_table('trade_ins',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=True),
    sa.Column('brand', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=120), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('km', sa.Integer(), nullable=True),
    sa.Column('plate', sa.String(length=20), nullable=True),
    sa.Column('condition', sa.String(length=200), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
    sa.Column('offered_value', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_ins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_ins_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_ins_organization_id'), ['organization_id'], unique=False)

    op.create_table('quotes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=True),
    sa.Column('vehicle_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('trade_in_value', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('expenses', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('financing_scenario_id', sa.String(length=32), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financing_scenario_id'], ['financing_scenarios.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index('ix_quotes_org_number', ['organization_id', 'number'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_quotes_organization_id'))
        batch_op.drop_index('ix_quotes_org_number')
        batch_op.drop_index(batch_op.f('ix_quotes_customer_id'))

    op.drop_table('quotes')
    with op.batch_alter_table('trade_ins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_ins_organization_id'))
        batch_op.drop_index(batch_op.f('ix_trade_ins_customer_id'))

    op.drop_table('trade_ins')
    with op.batch_alter_table('opportunity_stage_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_stage_history_organization_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_stage_history_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_stage_history_created_at'))

    op.drop_table('opportunity_stage_history')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_organization_id'))
        batch_op.drop_index(batch_op.f('ix_messages_customer_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.drop_index('ix_messages_conv_created')

    op.drop_table('messages')
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_followups_user_id'))
        batch_op.drop_index(batch_op.f('ix_followups_organization_id'))
        batch_op.drop_index('ix_followups_org_status_due')
        batch_op.drop_index(batch_op.f('ix_followups_due_at'))
        batch_op.drop_index(batch_op.f('ix_followups_customer_id'))

    op.drop_table('followups')
    with op.batch_alter_table('financing_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financing_scenarios_organization_id'))
        batch_op.drop_index(batch_op.f('ix_financing_scenarios_customer_id'))

    op.drop_table('financing_scenarios')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_organization_id'))
        batch_op.drop_index('ix_tasks_org_status_due')
        batch_op.drop_index(batch_op.f('ix_tasks_due_at'))

    op.drop_table('tasks')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_stage_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_organization_id'))
        batch_op.drop_index('ix_opportunities_org_status')
        batch_op.drop_index('ix_opportunities_org_stage')
        batch_op.drop_index(batch_op.f('ix_opportunities_customer_id'))

    op.drop_table('opportunities')
    with op.batch_alter_table('lead_score_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_score_history_organization_id'))
        batch_op.drop_index(batch_op.f('ix_lead_score_history_customer_id'))
        batch_op.drop_index(batch_op.f('ix_lead_score_history_created_at'))

    op.drop_table('lead_score_history')
    with op.batch_alter_table('customer_vehicle_matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_org_status')
        batch_op.drop_index(batch_op.f('ix_customer_vehicle_matches_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_customer_vehicle_matches_organization_id'))
        batch_op.drop_index(batch_op.f('ix_customer_vehicle_matches_customer_id'))

    op.drop_table('customer_vehicle_matches')
    op.drop_table('customer_tags')
    with op.batch_alter_table('customer_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_notes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_customer_notes_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customer_notes_created_at'))

    op.drop_table('customer_notes')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_organization_id'))
        batch_op.drop_index('ix_conversations_org_last')
        batch_op.drop_index(batch_op.f('ix_conversations_customer_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_user_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_starts_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_organization_id'))
        batch_op.drop_index('ix_appointments_org_starts')

    op.drop_table('appointments')
    with op.batch_alter_table('vehicle_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_status_history_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_status_history_organization_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_status_history_created_at'))

    op.drop_table('vehicle_status_history')
    with op.batch_alter_table('vehicle_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_images_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_images_organization_id'))

    op.drop_table('vehicle_images')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_organization_id'))
        batch_op.drop_index('ix_customers_org_status')
        batch_op.drop_index('ix_customers_org_score')
        batch_op.drop_index('ix_customers_org_assigned')
        batch_op.drop_index(batch_op.f('ix_customers_interested_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))
        batch_op.drop_index(batch_op.f('ix_customers_assigned_user_id'))

    op.drop_table('customers')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_plate'))
        batch_op.drop_index(batch_op.f('ix_vehicles_organization_id'))
        batch_op.drop_index('ix_vehicles_org_status')
        batch_op.drop_index('ix_vehicles_org_brand_model')

    op.drop_table('vehicles')
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segments_organization_id'))

    op.drop_table('segments')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_organization_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_dedup_key'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('automation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_automation_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_automation_runs_automation_id'))

    op.drop_table('automation_runs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_org_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_created_at'))

    op.drop_table('ai_usage')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_reset_token'))
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_organization_id'))

    op.drop_table('tags')
    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_stages_organization_id'))

    op.drop_table('pipeline_stages')
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_flags_organization_id'))

    op.drop_table('feature_flags')
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automations_organization_id'))

    op.drop_table('automations')
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.drop_index('ix_insights_org_kind_status')
        batch_op.drop_index(batch_op.f('ix_ai_insights_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ai_insights_dedup_key'))
        batch_op.drop_index(batch_op.f('ix_ai_insights_created_at'))

    op.drop_table('ai_insights')
    op.drop_table('organizations')
    # ### end Alembic commands ###
